config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { registrations: 'registrations' }

  get '/admins', to: 'admins#show'
  get '/newflight', to: 'phlights#new'
  get '/showflight', to: 'phlights#show'
  post '/newflight', to: 'phlights#create'
  get '/addairplane', to: 'phlights#addairplane'
  get '/addplanees', to: 'phlights#addplane'
  get '/newairplane', to: 'airplanes#new'
  post '/newairplane', to: 'airplanes#create'
  get '/newseatconfig', to: 'seatconfigs#new'
  post '/newseatconfig', to: 'seatconfigs#create'
  get '/newseatcat', to: 'seatcats#new'
  post '/newseatcat', to: 'seatcats#create'
  get '/newseatprofile', to: 'seats#new'
  post '/newseatprofile', to: 'seats#create'
  get '/showsconfig', to: 'seatconfigs#show'
  get '/addconfig', to: 'airplanes#add'
  get '/addconfiguration', to: 'airplanes#addconfiguration'
  get '/addconfig1', to: 'airplanes#postadd'
  get '/airplanesshow', to: 'airplanes#show'
  post '/search', to: 'searchs#createsearch'
  get '/search', to: 'searchs#error'
  get '/bookseat', to: 'bookings#new'
  post '/selectseaet', to: 'bookings#select'
  get '/selectinvalid', to: 'bookings#invalid'
  get '/seeprice', to: 'bookings#seeprice'
  get '/confirm', to: 'bookings#confirm'
  get 'modifybooking', to: 'bookings#modify'
  post '/addseat', to: 'bookings#addseat'
  post '/removeseat', to: 'bookings#removeseat'
  get '/conchan', to: 'bookings#conchange'
  get '/accept', to: 'bookings#accept'
  post '/pnr', to: 'searchs#pnr'
  get '/showbooking', to: 'bookings#show'
  get '/pnr', to: 'pages#logger'
  authenticated :user do
   root 'pages#logger', as: :authenticated_root
 end

 root to:'pages#index'

 resources :phlight
 resources :airplane
 resources :seatconfig do
   resources :seatcat do
     resources :seat

resources :booking do
  resources :tempseat
end
   end
 end

 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/airplane.rb
class Airplane < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :tempseats
  before_create :create_pnr

  def create_pnr
    loop do
  self.pnr = SecureRandom.hex(4)
  break unless self.class.exists?(:pnr => pnr)
end
  end
end

app/models/phlight.rb
class Phlight < ApplicationRecord
  validates :name, presence: true
  validates :origin, presence: true
  validates :destination, presence: true
  validates :fdate, presence: true
  validates :ftime, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :seatcat
end

app/models/seatcat.rb
class Seatcat < ApplicationRecord
  belongs_to :seatconfig
  has_many :seats
  validates :name, presence: true
  validates :row, presence: true
  validates :column, presence: true
  validates :baseprice, presence: true
end

app/models/seatconfig.rb
class Seatconfig < ApplicationRecord
  has_many :seatcats
  validates :name, presence: true
end

app/models/tempseat.rb
class Tempseat < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do

              concat message
            end)
    end
    nil
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phlights_helper.rb
module PhlightsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/seatcats_helper.rb
module SeatcatsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/tempseats_helper.rb
module TempseatsHelper
end

app/views/admins/_stats.html.erb
<h1>Stats</h1>
<% if !Search.exists? %>
<h5>No stats Available yet </h5>
<%else%>
<% full=Search.select(:origin,:destination).group(:origin,:destination).having("count(*) > 1").size%>
<% origin = Search.select(:origin).group(:origin).having("count(*) > 1").size%>
<% destination= Search.select(:destination).group(:destination).having("count(*) > 1").size%>
<%origin.delete("")%>
<%destination.delete("")%>
<%if full.nil? %>
<h4>Most Famous Flight Route </h4>
<h5>Origin:</h5>
<%= full.key(full.values.max).first %>
<h5>Destination:</h5>
<%= full.key(full.values.max).second %>
<%end%>

<br>
<Br>

  <h4>Most Famous Origin</h4>
  <%= origin.key(origin.values.compact.max) %>
  <br>
  <Br>
    <h4>Most Famous Destination</h4>
    <%= destination.key(destination.values.compact.max) %>
<%end%>

app/views/admins/show.html.erb
<div class="center">
  <h1>Admin Panel</h1>
<%= link_to "Create New Flight", newflight_path, class:"btn btn-outline-info" %>
<%= link_to "Display All Flights", showflight_path, class:"btn btn-outline-success" %>
<%= link_to "Add an Airplane", newairplane_path, class:"btn btn-outline-secondary" %>
<%= link_to "Existing Airplanes", airplanesshow_path, class:"btn btn-outline-primary"%>
<%= link_to "Create New Seat Configuration", newseatconfig_path, class:"btn btn-outline-dark" %>
<%= link_to "Existing Seat Configurations", showsconfig_path, class:"btn btn-outline-warning"%>
<br>
<br>
<br>
<%=render 'stats'%>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <div class="center">
    <br>
    <br>

  <h2><%=current_user.name.upcase %>
  </h2>

  <br>
  <br>
  <br>
  <br>
    <br>
    <br>
  <%if current_user.admin?%>
  <%= link_to "Admin Panel", admins_path, class:"btn btn-outline-info"%>
  <%end%>
  <br>
  <br>
  <%= link_to "Home", root_path, class:"btn btn-outline-success"%>

<br>
<br>
  <h5>Total Bookings:</h5>
  <%user_bookings=Booking.where(user_id: current_user.id)%>
  <%=user_bookings.count%>
<br>


  <div class="row bottom">
    <div class="col-sm-4">
      <%= link_to 'Log out', destroy_user_session_path, class:"sidelink" %>
      </div>
      <div class="col-sm-4">
        <%= link_to "Home", root_path, class:"sidelink"%>
        </div>
        <div class="col-sm-4">
          <%= link_to 'Profile', edit_user_registration_path, class:"sidelink" %>
          </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !user_signed_in? %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          </li>

        </ul>
<ul class="navbar-nav ml-auto">
  <%= form_tag(pnr_path, class:"form-inline my-2 my-lg-0") do %>

   <%=text_field_tag :store, "", class:'form-control mr-sm-2', placeholder: 'Search PNR'%>
  <%= submit_tag 'Search' , class:"btn btn-outline-success my-2 my-sm-0"%>
<% end %>

  <li class="nav-item">

      <%= link_to 'Log In', new_user_session_path, class:"nav-link" %>

    </li>
    <li class="nav-item">

      <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>

    </li>

  </ul>
      </div>
    </nav>
  <%end%>
    <%= yield :top_content %>
    <%if user_signed_in?%>
      <%= render 'layouts/sidebar'%>
      <%end%>
    <div class="bodycontainer" >
      <%if user_signed_in?%>
      <div class="topbar">
        <%= form_tag(pnr_path, class:"form-inline my-2 my-lg-0") do %>

         <%=text_field_tag :store, "", class:'form-control mr-sm-2', placeholder: 'Search PNR'%>
        <%= submit_tag 'Search' , class:"btn btn-outline-success my-2 my-sm-0"%>
      <% end %>
      <br>
      <br>
        </div>
        <%end%>
<%= flash_messages %>
<br>
          <%= yield %>
      </div>
  </body>
</html>