config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { registrations: 'registrations' }

  get '/admins', to: 'admins#show'
  get '/newflight', to: 'phlights#new'
  get '/showflight', to: 'phlights#show'
  post '/newflight', to: 'phlights#create'
  get '/addairplane', to: 'phlights#addairplane'
  get '/addplanees', to: 'phlights#addplane'
  get '/newairplane', to: 'airplanes#new'
  post '/newairplane', to: 'airplanes#create'
  get '/newseatconfig', to: 'seatconfigs#new'
  post '/newseatconfig', to: 'seatconfigs#create'
  get '/newseatcat', to: 'seatcats#new'
  post '/newseatcat', to: 'seatcats#create'
  get '/newseatprofile', to: 'seats#new'
  post '/newseatprofile', to: 'seats#create'
  get '/showsconfig', to: 'seatconfigs#show'
  get '/addconfig', to: 'airplanes#add'
  get '/addconfiguration', to: 'airplanes#addconfiguration'
  get '/addconfig1', to: 'airplanes#postadd'
  get '/airplanesshow', to: 'airplanes#show'
  post '/search', to: 'searchs#createsearch'
  get '/search', to: 'searchs#error'
  get '/bookseat', to: 'bookings#new'
  post '/selectseaet', to: 'bookings#select'
  get '/selectinvalid', to: 'bookings#invalid'
  get '/seeprice', to: 'bookings#seeprice'
  get '/confirm', to: 'bookings#confirm'
  get 'modifybooking', to: 'bookings#modify'
  post '/addseat', to: 'bookings#addseat'
  post '/removeseat', to: 'bookings#removeseat'
  get '/conchan', to: 'bookings#conchange'
  get '/accept', to: 'bookings#accept'
  post '/pnr', to: 'searchs#pnr'
  get '/showbooking', to: 'bookings#show'
  get '/pnr', to: 'pages#logger'
  authenticated :user do
   root 'pages#logger', as: :authenticated_root
 end

 root to:'pages#index'

 resources :phlight
 resources :airplane
 resources :seatconfig do
   resources :seatcat do
     resources :seat

resources :booking do
  resources :tempseat
end
   end
 end

 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/airplane.rb
class Airplane < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :tempseats
  before_create :create_pnr

  def create_pnr
    loop do
  self.pnr = SecureRandom.hex(4)
  break unless self.class.exists?(:pnr => pnr)
end
  end
end

app/models/phlight.rb
class Phlight < ApplicationRecord
  validates :name, presence: true
  validates :origin, presence: true
  validates :destination, presence: true
  validates :fdate, presence: true
  validates :ftime, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :seatcat
end

app/models/seatcat.rb
class Seatcat < ApplicationRecord
  belongs_to :seatconfig
  has_many :seats
  validates :name, presence: true
  validates :row, presence: true
  validates :column, presence: true
  validates :baseprice, presence: true
end

app/models/seatconfig.rb
class Seatconfig < ApplicationRecord
  has_many :seatcats
  validates :name, presence: true
end

app/models/tempseat.rb
class Tempseat < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/phlights_controller.rb
class PhlightsController < ApplicationController
  def new
    @phlight=Phlight.new
  end

  def show
  end

  def create
    @phlight= Phlight.create(phlight_params)
    if @phlight.save
      flash[:success]="Flight Added. Add Airplane"
      redirect_to addairplane_path(:phlight_id=> @phlight.id)
    else
      flash[:danger]="Cannot be saved"
      render 'new'
    end
  end

  def addairplane
  end

def addplane
  @airplane=Airplane.find(params[:airplane_id])
  @phlight= Phlight.find(params[:phlight_id])
  @ap=Airplane.create(:name=>@airplane.name, :show=>false)
  @scon= Seatconfig.find(@airplane.seatconfig_id)
  @nscon=Seatconfig.create(:name=>@scon.name, :show=>false)
  @ap.update(:seatconfig_id=>@nscon.id)
  @scon.seatcats.each do |a|
    number=1
  @nscat= @nscon.seatcats.create(:name=>a.name,:row => a.row, :column=> a.column, :baseprice=> a.baseprice)
  a.row.times do |r|
    a.column.times do |c|
      @fs=@nscat.seats.create()
      @fs.update_column(:number, number)
      number=number+1
      @fs.update_column(:break, a.column)
        if @fs.number % @fs.break == 0 || @fs.number % @fs.break == 1
        @fs.update_column(:position, "window")
        end

        if a.column%2==0
          if @fs.number % (a.column/2)==0 || @fs.number % (a.column/2)==1
          if @fs.position === "window"
          else
          @fs.update_column(:position, "aisle")
          end
        end
      else
        if (@fs.number+(a.column/2))% a.column==0 || (@fs.number+((a.column/2)-1))%a.column==0
        if @fs.position === "window"
        else
        @fs.update_column(:position, "aisle")
        end
      end
      end

    end
    end
    end
  @phlight.update(:airplane_id=> @ap.id)

  flash[:success]="Airplane has been added successfully"
  redirect_to root_path
end

  private
  def phlight_params
    params.require(:phlight).permit(:name, :origin, :destination, :fdate, :ftime)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do

              concat message
            end)
    end
    nil
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phlights_helper.rb
module PhlightsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/seatcats_helper.rb
module SeatcatsHelper
end

app/helpers/seatconfigs_helper.rb
module SeatconfigsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/tempseats_helper.rb
module TempseatsHelper
end

app/views/phlights/_phlight.html.erb
<div class="col-sm-6">
  <div class="fdetails">
    <br>
  <h5> Name:</h5>
  <h5>
<%= phlight.name %>
</h5>
<br>
  <h5> Origin:</h5>
  <h5>
<%= phlight.origin %>
</h5>
<br>
  <h5> Destination:</h5>
  <h5>
<%= phlight.destination %>
</h5>
<br>
<h5> Date:</h5>
<h5>
<%= phlight.fdate %>
</h5>
<br>
<h5> Time:</h5>
<h5>
<%= phlight.ftime.strftime("%I:%M")%>
</h5>
<br>
<h5> Airplane:</h5>
<%if !phlight.airplane_id.nil?%>
<%@airplane=Airplane.find(phlight.airplane_id)%>
<%@scon=Seatconfig.find(@airplane.seatconfig_id) %>
<h5>
<%=@airplane.name %>
</h5>
<%else%>
<%= link_to "Add Airplane", addairplane_path(:phlight_id=> phlight.id), class:"btn btn-outline-success"%>
<%end%>
<br>
</div>
<br>

<br>

<%if !phlight.airplane_id.nil?%>
<%=render @scon.seatcats.order(:id)%>
<%end%>

<br>
</div>

app/views/phlights/addairplane.html.erb
<div class="center">
<h1>Add Airplane to the Flight</h1>
<br>
<br>
<% @phlight=Phlight.find(params[:phlight_id]) %>

<% Airplane.where(show: true).each do |a| %>

<%@scon=Seatconfig.find(a.seatconfig_id) %>
<h5>

<%=@scon.name%>
</h5>
<%=render @scon.seatcats.order(:id)%>

<br>
<%= link_to "Add Airplane", addplanees_path(:airplane_id=> a.id, :phlight_id=> @phlight.id), class:"btn btn-outline-success"%>
<%end%>
</div>

app/views/phlights/new.html.erb
<h1 class="center">Create A New Flight</h1>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
<%= form_for(@phlight, url: newflight_path) do |f| %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :origin %>
<%= f.text_field :origin, class: 'form-control' %>

<%= f.label :destination %>
<%= f.text_field :destination, class: 'form-control' %>

<%= f.label :date%>
<%= f.date_field :fdate, class: 'form-control' %>

<%= f.label :time%>
<%= f.time_field :ftime, class: 'form-control' %>
<br>
<div class="center">
<%= f.submit "Create Flight", class: "btn btn-outline-info btn-lg" %>
</div>
<% end %>
</div>
</div>

app/views/phlights/show.html.erb
<div class="center">
<h1>All Flights</h1>
<br>
<br>
<br>
<div class="row flight">
<%= render Phlight.all %>
</div>
</div>