config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { registrations: 'registrations' }

  get '/admins', to: 'admins#show'
  get '/newflight', to: 'phlights#new'
  get '/showflight', to: 'phlights#show'
  post '/newflight', to: 'phlights#create'
  get '/addairplane', to: 'phlights#addairplane'
  get '/addplanees', to: 'phlights#addplane'
  get '/newairplane', to: 'airplanes#new'
  post '/newairplane', to: 'airplanes#create'
  get '/newseatconfig', to: 'seatconfigs#new'
  post '/newseatconfig', to: 'seatconfigs#create'
  get '/newseatcat', to: 'seatcats#new'
  post '/newseatcat', to: 'seatcats#create'
  get '/newseatprofile', to: 'seats#new'
  post '/newseatprofile', to: 'seats#create'
  get '/showsconfig', to: 'seatconfigs#show'
  get '/addconfig', to: 'airplanes#add'
  get '/addconfiguration', to: 'airplanes#addconfiguration'
  get '/addconfig1', to: 'airplanes#postadd'
  get '/airplanesshow', to: 'airplanes#show'
  post '/search', to: 'searchs#createsearch'
  get '/search', to: 'searchs#error'
  get '/bookseat', to: 'bookings#new'
  post '/selectseaet', to: 'bookings#select'
  get '/selectinvalid', to: 'bookings#invalid'
  get '/seeprice', to: 'bookings#seeprice'
  get '/confirm', to: 'bookings#confirm'
  get 'modifybooking', to: 'bookings#modify'
  post '/addseat', to: 'bookings#addseat'
  post '/removeseat', to: 'bookings#removeseat'
  get '/conchan', to: 'bookings#conchange'
  get '/accept', to: 'bookings#accept'
  post '/pnr', to: 'searchs#pnr'
  get '/showbooking', to: 'bookings#show'
  get '/pnr', to: 'pages#logger'
  authenticated :user do
   root 'pages#logger', as: :authenticated_root
 end

 root to:'pages#index'

 resources :phlight
 resources :airplane
 resources :seatconfig do
   resources :seatcat do
     resources :seat

resources :booking do
  resources :tempseat
end
   end
 end

 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/airplane.rb
class Airplane < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :tempseats
  before_create :create_pnr

  def create_pnr
    loop do
  self.pnr = SecureRandom.hex(4)
  break unless self.class.exists?(:pnr => pnr)
end
  end
end

app/models/phlight.rb
class Phlight < ApplicationRecord
  validates :name, presence: true
  validates :origin, presence: true
  validates :destination, presence: true
  validates :fdate, presence: true
  validates :ftime, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :seatcat
end

app/models/seatcat.rb
class Seatcat < ApplicationRecord
  belongs_to :seatconfig
  has_many :seats
  validates :name, presence: true
  validates :row, presence: true
  validates :column, presence: true
  validates :baseprice, presence: true
end

app/models/seatconfig.rb
class Seatconfig < ApplicationRecord
  has_many :seatcats
  validates :name, presence: true
end

app/models/tempseat.rb
class Tempseat < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @left=Booking.where(confirm: true)
    @left.each do |l|
      if l.tempseats.count==0
        @left.destroy(l.id)
      end
    end
    @del=Booking.where(confirm: false)
    @del.each do |d|
      d.tempseats.destroy_all
    end
    @del.destroy_all
    @booking=Booking.create(:user_id=>current_user.id, :flight_id=>params[:flight_id])

  end


def show
@booking=Booking.find(params[:booking_id])
end

def select
  @booking=Booking.find(params[:booking_id])
  @seat=Seat.find(params[:seat_id])
  @secat= @seat.seatcat
  if @booking.tempseats.where(seat_id: @seat.id).exists?
     d=@booking.tempseats.where(seat_id: @seat.id)
    @booking.tempseats.destroy(d.first.id)
  else
  @booking.tempseats.create(:price=>@secat.baseprice, :seat_id=>@seat.id, :emergency=>@seat.emergency, :booking_id=>@booking.id, :position=>@seat.position, :final=> true)
end
end

def seeprice
  @booking=Booking.find(params[:booking_id])

end
def confirm
  @booking=Booking.find(params[:booking_id])
  flash[:success]="Booking has been successful"
  @booking.update_column(:confirm, true)
  @booking.tempseats.each do |b|
    @seat=Seat.find(b.seat_id)
    @seat.update_column(:available, false)
    @seat.update_column(:booking_id, @booking.id)
  end
  redirect_to root_path
end

def invalid
flash[:danger]="Seat not available"
redirect_back(fallback_location: root_path)
end

def modify
    @des=Tempseat.where(final: false, old: false)
    @des.each do |ds|
    puts ds.id
    puts "modify des destroy"
    Tempseat.destroy(ds.id)
  end

  @del=Booking.where(confirm: false)
  @del.each do |d|
    d.tempseats.destroy_all
  end
  @del.destroy_all
  @booking=Booking.find(params[:booking_id])
  @booking=Booking.find(params[:booking_id])
  @flight=Phlight.find(@booking.flight_id)
  @airplane=Airplane.find(@flight.airplane_id)
  @seatconfig=Seatconfig.find(@airplane.seatconfig_id)
end
def addseat
  @booking=Booking.find(params[:booking_id])
  @price=@booking.tprice
  @seat=Seat.find(params[:seat_id])
  query=@booking.tempseats.where(seat_id: @seat.id)
  if query.exists?
    query.destroy_all
    if @seat.position==="middle"
      @price=@price-@seat.seatcat.baseprice
    else
      @price=@price-@seat.seatcat.baseprice-(0.5*@seat.seatcat.baseprice)
    end
    else
      if @seat.position==="middle"
        @price=@price+@seat.seatcat.baseprice
      else
        @price=@price+@seat.seatcat.baseprice+(0.5*@seat.seatcat.baseprice)
      end
      @booking.tempseats.create(:seat_id=>@seat.id, :emergency=> @seat.emergency, :position=>@seat.position, :old=> false, :final=>true)
    end
    @booking.update_column(:tprice, @price)

end

def removeseat
  @booking=Booking.find(params[:booking_id])
  @price=@booking.tprice
  @seat=Seat.find(params[:seat_id])
  query=@booking.tempseats.where(seat_id: @seat.id).first
  query.toggle!(:final)
  if query.final
  if @seat.position==="middle"
    @price=@price+@seat.seatcat.baseprice
  else
    @price=@price+@seat.seatcat.baseprice
   end
 else
   if @seat.position==="middle"
     @price=@price-@seat.seatcat.baseprice
   else
     @price=@price-@seat.seatcat.baseprice
    end
  end
   @booking.update_column(:tprice, @price)
end

def accept
  @booking=Booking.find(params[:booking_id])
  price=@booking.price+@booking.tprice
  @booking.update_column(:price, price)
  tempold=@booking.tempseats.where(:final=>false)
  tempold.each do |t|
    seat=Seat.find(t.seat_id)
    seat.update(:available=> true, :booking_id=>nil)
  end
  tempold.destroy_all
  tempnew=@booking.tempseats.where(:old=> false, :final=>true)
  tempnew.each do |n|
    n.update_column(:old, true)
    s=Seat.find(n.seat_id)
    s.update(:available=> false, :booking_id=> @booking.id)
  end
  flash[:success]="Modifications made"
  redirect_to root_path
  end


def conchange
  @booking=Booking.find(params[:booking_id])
end

def change

end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do

              concat message
            end)
    end
    nil
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phlights_helper.rb
module PhlightsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/seatcats_helper.rb
module SeatcatsHelper
end

app/helpers/seatconfigs_helper.rb
module SeatconfigsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/tempseats_helper.rb
module TempseatsHelper
end

app/views/bookings/_booking.html.erb
<div class="col-sm-6 center">
  <h3><%=booking.price%></h3>
<h4>Booking: <%=booking.id%></h4>
<%@flight=Phlight.find(booking.flight_id)%>
<h5>Flight: <%=@flight.id%></h5>
<%@airplane=Airplane.find(@flight.airplane_id)%>
<%@scon= Seatconfig.find(@airplane.seatconfig_id)%>
<%@secat=@scon.seatcats.order(:id)%>
<%@secat.each do |se|%>
<% @st=se.seats.order(:id) %>
<%@st.each do |a|%>

<%if a.booking_id==booking.id%>
<div class="seatcontainer-light">
<div class="hidden">.</div></div>
<%else%>
<div class="seatcontainer-dark">
<div class="hidden">.</div></div>
<%end%>
<%if a.position=== "aisle" && Seat.find((a.id+1)).position==="aisle"%>
<div class="seatcontainer-empty">
<div class="hidden">.</div></div>
<%end%>
<%if a.number % a.break==0%>
<br>
<%end%>
<%end%>
<br>
<%end%>
<br>
<%if current_user===User.find(booking.user_id)%>
<%= link_to "Modify Booking", modifybooking_path(:booking_id=> booking.id), class:"btn btn-outline-info"%>
<%else%>
<%end%>
</div>

app/views/bookings/conchange.html.erb
<div class="center">
<h1>Confirm Changes</h1>
<h4>New Price</h4>
<%=@booking.tprice%>
<br>
<br>
<%= link_to "Accept", accept_path(:booking_id=>@booking.id), class:"btn btn-outline-success"%>
</div>

app/views/bookings/modify.html.erb
<div class="center">
<div class="row">
  <div class="col-6">
<h1>Modify Your Booking</h1>
<%@temp=@booking.tempseats.order(:id)%>

<br>
<%@seatconfig.seatcats.order(:id).each do |s|%>
<%s.seats.order(:id).each do|seat|%>
<%arr=Seat.where(booking_id: @booking.id).ids%>
<%if seat.id.in?arr%>
<div class="seatcontainer-your">
  <%= button_to "", removeseat_path(:booking_id=>@booking.id, :seat_id=> seat.id), method: :post, class:"seat seatcontainer-your",  onclick:"this.classList.toggle('colchangerem')"%>
</div>
<%else%>
<% if seat.available%>
<div class="seatcontainer-dark">
<%= button_to "", addseat_path(:booking_id=>@booking.id, :seat_id=> seat.id), method: :post, class:"seat seatcontainer-dark",  onclick:"this.classList.toggle('colchange')"%>
</div>
<%else%>
<div class="seatcontainer-light"><div class="hidden">.</div></div>
<%end%>
<%end%>
<%if seat.position=== "aisle"%>
<%if Seat.last.id>seat.id+1 %>
<% if  Seat.find((seat.id+1)).position==="aisle"%>
<div class="seatcontainer-empty">
<div class="hidden">.</div></div>
<%end%>
<%end%>
<%end%>
<% if seat.number % seat.break ==0 %>
<br>
<%end%>
<%end%>
<br>
<%end%>

<%= link_to "Confirm Changes", conchan_path(:booking_id=> @booking.id), class:"btn btn-outline-success"%>
</div>
  </div>
  </div>

app/views/bookings/new.html.erb
<div class="center">
  <h1>Book Your Ticket</h1>
  <%@flight= Phlight.find(params[:flight_id])%>
  <% @apid=@flight.airplane_id %>
  <%@ap=Airplane.find(@apid)%>
  <%@scid=@ap.seatconfig_id%>
  <% @sc=Seatconfig.find(@scid)%>
  <%ss=@sc.seatcats.order(:id)%>
  <%ss.each do |s|%>
  <%=s.name%>
  <br>
    <%s1=s.seats.order(:id)%>
    <%s1.each do |fs|%>

    <% if fs.available %>
    <div class="seatcontainer-dark">
      <%=button_to "", selectseaet_path(:seat_id=> fs.id, :booking_id=> @booking.id), method: :post, class:"seat",  onclick:"this.classList.toggle('colchange')"%>
    </div>
      <%else%>
      <div class="seatcontainer-light">
        <%=link_to "", selectinvalid_path(:seat_id=> fs.id), class:"seat"%>
    </div>
    <%end%>
    <%if fs.position=== "aisle" && Seat.find((fs.id+1)).position==="aisle"%>
    <div class="seatcontainer-empty">
    <div class="hidden">.</div></div>
    <%end%>
    <%if fs.number % fs.break==0%>
    <br>
    <%end%>
    <%end%>
  <br>
  <%end%>

  <%= link_to "Check Price", seeprice_path(:booking_id=>@booking.id), class:"btn btn-outline-info"%>
</div>

app/views/bookings/seeprice.html.erb
<div class="center">
<h1>Confirm Your Booking</h1>
<br>
<div class="row">
<%=render @booking.tempseats%>
</div>
<br>
<%p=0%>
<% @booking.tempseats.each do |t| %>
<% if t.position==="middle"%>
<%p=p+t.price%>
<%else%>
<%q= (0.5*t.price)+t.price%>
<%p=p+q%>
<%end%>
<%end%>
<%@booking.update(price: p, tprice: 0)%>
<h3>Total Price:</h3>
<%=@booking.price%>
<br>
<br>
<%=link_to "Confirm", confirm_path(:booking_id=>@booking.id), class:"btn btn-outline-success"%>
</div>

app/views/bookings/show.html.erb
<%=render @booking%>