config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { registrations: 'registrations' }

  get '/admins', to: 'admins#show'
  get '/newflight', to: 'phlights#new'
  get '/showflight', to: 'phlights#show'
  post '/newflight', to: 'phlights#create'
  get '/addairplane', to: 'phlights#addairplane'
  get '/addplanees', to: 'phlights#addplane'
  get '/newairplane', to: 'airplanes#new'
  post '/newairplane', to: 'airplanes#create'
  get '/newseatconfig', to: 'seatconfigs#new'
  post '/newseatconfig', to: 'seatconfigs#create'
  get '/newseatcat', to: 'seatcats#new'
  post '/newseatcat', to: 'seatcats#create'
  get '/newseatprofile', to: 'seats#new'
  post '/newseatprofile', to: 'seats#create'
  get '/showsconfig', to: 'seatconfigs#show'
  get '/addconfig', to: 'airplanes#add'
  get '/addconfiguration', to: 'airplanes#addconfiguration'
  get '/addconfig1', to: 'airplanes#postadd'
  get '/airplanesshow', to: 'airplanes#show'
  post '/search', to: 'searchs#createsearch'
  get '/search', to: 'searchs#error'
  get '/bookseat', to: 'bookings#new'
  post '/selectseaet', to: 'bookings#select'
  get '/selectinvalid', to: 'bookings#invalid'
  get '/seeprice', to: 'bookings#seeprice'
  get '/confirm', to: 'bookings#confirm'
  get 'modifybooking', to: 'bookings#modify'
  post '/addseat', to: 'bookings#addseat'
  post '/removeseat', to: 'bookings#removeseat'
  get '/conchan', to: 'bookings#conchange'
  get '/accept', to: 'bookings#accept'
  post '/pnr', to: 'searchs#pnr'
  get '/showbooking', to: 'bookings#show'
  get '/pnr', to: 'pages#logger'
  authenticated :user do
   root 'pages#logger', as: :authenticated_root
 end

 root to:'pages#index'

 resources :phlight
 resources :airplane
 resources :seatconfig do
   resources :seatcat do
     resources :seat

resources :booking do
  resources :tempseat
end
   end
 end

 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/airplane.rb
class Airplane < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :tempseats
  before_create :create_pnr

  def create_pnr
    loop do
  self.pnr = SecureRandom.hex(4)
  break unless self.class.exists?(:pnr => pnr)
end
  end
end

app/models/phlight.rb
class Phlight < ApplicationRecord
  validates :name, presence: true
  validates :origin, presence: true
  validates :destination, presence: true
  validates :fdate, presence: true
  validates :ftime, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :seatcat
end

app/models/seatcat.rb
class Seatcat < ApplicationRecord
  belongs_to :seatconfig
  has_many :seats
  validates :name, presence: true
  validates :row, presence: true
  validates :column, presence: true
  validates :baseprice, presence: true
end

app/models/seatconfig.rb
class Seatconfig < ApplicationRecord
  has_many :seatcats
  validates :name, presence: true
end

app/models/tempseat.rb
class Tempseat < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def new
    @airplane= Airplane.new
  end

  def show
  end

  def create
    @airplane= Airplane.create(airplane_params)
    if @airplane.save
      flash[:success]="Airplane Added"
      redirect_to addconfig_path(:airplane_id => @airplane.id)
    else
      flash[:danger]="Cannot be saved"
      render 'new'
    end
  end

  def add
  end

  def addconfiguration
    @airplane=Airplane.find(params[:airplane_id])

  end

  def postadd
    @airplane=Airplane.find(params[:airplane_id])
    @seatconfig=Seatconfig.find(params[:seatconfig_id])
    @scnew=Seatconfig.create(:name=>@airplane.name)
    @scnew.update(:show=> false)
    @seatconfig.seatcats.each do |s|
      number=1;
        @sc=@scnew.seatcats.create(:name => s.name, :row => s.row, :column=> s.column, :baseprice=> s.baseprice)
      s.row.times do |r|
        s.column.times do |c|
          @fs=@sc.seats.create()
        @fs.update_column(:number, number)
        number=number+1
        @fs.update_column(:break, s.column)

          if @fs.number % @fs.break == 0 || @fs.number % @fs.break == 1
          @fs.update_column(:position, "window")
      
      end
        if s.column%2==0

          if @fs.number % (s.column/2)==0 || @fs.number % (s.column/2)==1
          if @fs.position === "window"
          else
          @fs.update_column(:position, "aisle")
          end
        end
      else
        if (@fs.number+(s.column/2))% s.column==0 || (@fs.number+((s.column/2)-1))%s.column==0
        if @fs.position === "window"
        else
        @fs.update_column(:position, "aisle")
        end
      end
      end
        end
    end
  end
    @airplane.update(:seatconfig_id=>@scnew.id)
    flash[:success]="added"
    redirect_to root_path
end


  private
  def airplane_params
    params.require(:airplane).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do

              concat message
            end)
    end
    nil
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phlights_helper.rb
module PhlightsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/seatcats_helper.rb
module SeatcatsHelper
end

app/helpers/seatconfigs_helper.rb
module SeatconfigsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/tempseats_helper.rb
module TempseatsHelper
end

app/views/airplanes/_airplane.html.erb
<%- airplanes.each do |airplane| %>
  <% if airplane.show %>
    <div class="col-sm-6">
    <br>
    <h1><%= airplane.name%></h1>
    <% seatconfig=Seatconfig.find(airplane.seatconfig_id)%>
    <%= render seatconfig.seatcats.order(:id)%>
    <br>
    <%= link_to "Change Seat Config", addconfiguration_path(:airplane_id=>airplane.id, :seatconfig_id=>seatconfig.id), class:"btn btn-outline-success"%>
    </div>
  <%end%>
<% end %>

app/views/airplanes/add.html.erb
<div class="center">
<% @airplane= Airplane.find(params[:airplane_id])%>
<h1><%= @airplane.name %></h1>

<%if @airplane.seatconfig_id.nil?%>
<h3>No seat configurations added yet.</h3>
<br>
<%= link_to "Create New Config for this Airplane", newseatconfig_path, class:"btn btn-outline-info"%>
<%= link_to "Add Existing Config", addconfiguration_path(:airplane_id=>@airplane.id), class:"btn btn-outline-success"%>
<%else%>
<%@seatconfig= Seatconfig.find(@airplane.seatconfig_id)%>
<%= render @seatconfig.seatcats.order(:id) %>
<%end%>
</div>

app/views/airplanes/addconfiguration.html.erb
<div class="center">
<h1>Add Existing Configuration</h1>
<br>
<br>
<div class="row">
<%= render Seatconfig.where(show: true)%>
</div>
</div>

app/views/airplanes/new.html.erb
<h1 class="center"> Add an Airplane </h1>
<div class="row">
<div class="col-sm-6 offset-sm-3">
<%= form_for(@airplane, url: newairplane_path) do |f| %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
<br>
<div class="center">
<%= f.submit "Add the Airplane", class: "btn btn-outline-info btn-lg" %>
</div>
<% end %>
</div>
</div>

app/views/airplanes/postadd.html.erb
<h1>Added</h1>

app/views/airplanes/show.html.erb
<div class="center">
<h1> List of Airplanes </h1>
<div class="row">
<%= render 'airplane', airplanes: Airplane.where(show: true)%>
</div>
</div>